// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addPlayer = `-- name: AddPlayer :one
INSERT INTO players (avatar, nickname, latest_session_id) VALUES (?, ?, ?) RETURNING id, created_at, updated_at, avatar, nickname, disconnected_at, latest_session_id
`

type AddPlayerParams struct {
	Avatar          []byte
	Nickname        string
	LatestSessionID int64
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, addPlayer, arg.Avatar, arg.Nickname, arg.LatestSessionID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Nickname,
		&i.DisconnectedAt,
		&i.LatestSessionID,
	)
	return i, err
}

const addRoom = `-- name: AddRoom :one
INSERT INTO rooms (game_name, host_player, room_code) VALUES (?, ?, ?) RETURNING id, created_at, updated_at, game_name, host_player, room_code
`

type AddRoomParams struct {
	GameName   string
	HostPlayer string
	RoomCode   string
}

func (q *Queries) AddRoom(ctx context.Context, arg AddRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, addRoom, arg.GameName, arg.HostPlayer, arg.RoomCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GameName,
		&i.HostPlayer,
		&i.RoomCode,
	)
	return i, err
}

const addRoomPlayer = `-- name: AddRoomPlayer :one
INSERT INTO rooms_players (room_id, player_id) VALUES (?, ?) RETURNING room_id, player_id, created_at, updated_at
`

type AddRoomPlayerParams struct {
	RoomID   string
	PlayerID string
}

func (q *Queries) AddRoomPlayer(ctx context.Context, arg AddRoomPlayerParams) (RoomsPlayer, error) {
	row := q.db.QueryRowContext(ctx, addRoomPlayer, arg.RoomID, arg.PlayerID)
	var i RoomsPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPlayersInRoom = `-- name: GetAllPlayersInRoom :many
SELECT p.id, p.created_at, p.updated_at, p.avatar, p.nickname, p.disconnected_at, p.latest_session_id, r.room_code
FROM players p
JOIN rooms_players rp ON p.id = rp.player_id
JOIN rooms r ON rp.room_id = r.id
WHERE rp.room_id IN (
    SELECT room_id
    FROM rooms_players
    WHERE rp.player_id = ?
)
`

type GetAllPlayersInRoomRow struct {
	ID              string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	Avatar          []byte
	Nickname        string
	DisconnectedAt  sql.NullTime
	LatestSessionID int64
	RoomCode        string
}

func (q *Queries) GetAllPlayersInRoom(ctx context.Context, playerID string) ([]GetAllPlayersInRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayersInRoom, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPlayersInRoomRow
	for rows.Next() {
		var i GetAllPlayersInRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
			&i.Nickname,
			&i.DisconnectedAt,
			&i.LatestSessionID,
			&i.RoomCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNickname = `-- name: UpdateNickname :one
UPDATE players SET nickname = ? WHERE id = ? RETURNING id, created_at, updated_at, avatar, nickname, disconnected_at, latest_session_id
`

type UpdateNicknameParams struct {
	Nickname string
	ID       string
}

func (q *Queries) UpdateNickname(ctx context.Context, arg UpdateNicknameParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updateNickname, arg.Nickname, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Nickname,
		&i.DisconnectedAt,
		&i.LatestSessionID,
	)
	return i, err
}
